### ISSUE TITLE
Erreur "ValueError: Selected column type de l is not in uploaded header (can be different from the original file)"

### ISSUE THREAD

**Issue by duplau** [jerem1508/magical_ui#12]
Pour reproduire : nouveau fichier de normalisation (une 20aine de colonnes, demandez-moi un lien vers le fichier si impossible à reproduire) puis laisser toutes les colonnes sélectionnées, en cliquant sur "Etape suivante, détection des valeurs manquantes" rien ne se passe et j'ai le log d'erreur ci-dessous.

Je pense qu'on pourrait faire en 2 étape :
1. adresser ce bug spécifique (aucune idée si la chaîne envoyée depuis l'UI est en cause, ou la liste des headers côté backend, ou autre chose)
2. mettre en place une gestion *générique* des erreurs : sachant que nous n'aurons jamais corrigé ni anticipié 100% des cas d'erreur, il faut pouvoir les attraper afin de remonter un message dans l'UI, plutôt que le comportement actuel qui bloque l'UI (ni message d'erreur ni passage à la page suivante) et plante le process backend (même si uWSGI le relance automatiquement).

```
Traceback (most recent call last):
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/magical_laundry/laundry_env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 1285, in add_selected_columns
    proj.add_selected_columns(selected_columns)    
  File "./normalizer.py", line 321, in add_selected_columns
    col, self.metadata['column_tracker']['original']))
ValueError: Selected column type de l is not in uploaded header (can be different from the original file)
 --> uploaded header: (['Localisation', 'Etablissement siège', "type de l'établissement siège", 'Implantation', 'Géolocalisation', 'Nature', 'Service', "Date d'ouverture", "Effectif d'étudiants inscrits", 'Type', "Code de l'implantation", "Code de l'unité de rattachement", 'Unité de rattachement', "Code de l'établissement siège", "sigle de l'établissement siège", 'Identifiant ETER', 'Identifiant wikidata', 'Elément wikidata', 'Identifiant GRID', 'element_grid', 'Code commune', 'Commune', 'Code unité urbaine', 'Unité urbaine', 'Code département', 'Département', 'Code académie', 'Académie', 'Code région', 'Région', 'Code pays', 'Mention de distribution', 'Adresse', 'Lieu dit', 'Boite postale', 'Code postal', 'Localité', 'Pays', 'Code type', 'Code nature'])
```

**Comment by duplau** [comment]
Ce bug n'apparaît plus, et comme la question du traitement générique des erreurs est adressée par #8 , je ferme celui-ci.
