### ISSUE TITLE
bug à cause d'un type code INSEE défini dans un fichier

### ISSUE THREAD

**Issue by yaca29** [jerem1508/magical_ui#84]
dans la procédure de jointure, lors de l'association des colonnes, bug à cause d'un type Code INSEE

cf message dans la console :
```
jQuery.Deferred exception: Cannot read property 'Code INSEE' of undefined TypeError: Cannot read property 'Code INSEE' of undefined
    at eval (eval at get_columns_html (http://51.15.221.77/assets/project_link_select_columns.js:44:18), <anonymous>:1:10)
    at get_columns_html (http://51.15.221.77/assets/project_link_select_columns.js:44:18)
    at HTMLDocument.<anonymous> (http://51.15.221.77/index.php/Project/link/eedeb943bb2683b0cb5c21cbc6b59a43:599:28)
    at j (http://51.15.221.77/assets/jquery-3.2.1.min.js:2:29999)
    at k (http://51.15.221.77/assets/jquery-3.2.1.min.js:2:30313) undefined
```

**Comment by Leobouloc** [comment]
Ce bug est il toujours d'actualité? Si oui, y a t'il un fichier permettant de le reproduire ?

**Comment by Leobouloc** [comment]
pas reproduit récemment
